-- =============================================================================
-- MediStock (Smart HAS) - Parte 3: functions, procedures e alertas em PL/SQL
--
-- Execute com F5 como MEDISTOCK / FREEPDB1, depois dos scripts 00 a 03.
-- Pode ser reexecutado: cria ALERTAS somente se ainda nao existir e
-- recria view, functions e procedures com CREATE OR REPLACE. Nao altera
-- nem apaga as tabelas e os dados da Parte 2.
--
-- Conteudo:
--   1. Tabela ALERTAS e view VW_ALERTAS_VIGENTES
--   2. Functions  : fn_dias_cobertura_estoque, fn_status_estoque_formatado
--   3. Procedures : prc_registrar_alertas_criticos, prc_relatorio_consumo_hospital
--   Exemplos de uso: 07_parte3_exemplos.sql
--
-- Integracao com o back-end (Spring Boot, profile "oracle"):
--   - Ao criar/atualizar um item de estoque, o back-end publica um evento e,
--     apos o commit, chama prc_registrar_alertas_criticos via JDBC.
--   - A procedure tambem roda ao iniciar a API e diariamente as 00:05.
--   - A tela de Alertas le VW_ALERTAS_VIGENTES.
--   - Endpoints em /api/plsql expoem as procedures e as functions.
--
-- Codigos de erro desta parte: faixa -20101 a -20121 (os codigos -20001 a
-- -20005 pertencem a PR_REGISTRAR_CONSUMO).
-- =============================================================================
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

BEGIN
    IF SYS_CONTEXT('USERENV', 'SESSION_USER') <> 'MEDISTOCK'
       OR SYS_CONTEXT('USERENV', 'CON_NAME') <> 'FREEPDB1' THEN
        RAISE_APPLICATION_ERROR(-20090,
            'Execute este arquivo na conexao MEDISTOCK do FREEPDB1.');
    END IF;
END;
/


-- =============================================================================
-- 1. TABELA ALERTAS E VIEW VW_ALERTAS_VIGENTES
-- =============================================================================

-- Historico auditavel dos alertas gravados por prc_registrar_alertas_criticos.
CREATE TABLE IF NOT EXISTS ALERTAS (
    ID NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ITEM_ESTOQUE_ID NUMBER(19,0),
    HOSPITAL_ID NUMBER(19,0),
    TIPO VARCHAR2(20 CHAR) NOT NULL,
    MENSAGEM VARCHAR2(400 CHAR) NOT NULL,
    ORIGEM VARCHAR2(150 CHAR),
    CRIADO_EM TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ALERTAS PRIMARY KEY (ID),
    CONSTRAINT CK_ALERTA_TIPO CHECK (TIPO IN ('CRITICO','ATENCAO','INFO')),
    CONSTRAINT FK_ALERTA_ITEM FOREIGN KEY (ITEM_ESTOQUE_ID) REFERENCES ITENS_ESTOQUE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ALERTA_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAIS(ID)
);

COMMENT ON TABLE ALERTAS IS 'Alertas de estoque e validade gravados pela procedure prc_registrar_alertas_criticos.';
COMMENT ON COLUMN ALERTAS.ID IS 'Chave primária; gerada pelo Oracle.';
COMMENT ON COLUMN ALERTAS.ITEM_ESTOQUE_ID IS 'FK para ITENS_ESTOQUE.ID; o alerta é removido junto com o item.';
COMMENT ON COLUMN ALERTAS.HOSPITAL_ID IS 'FK para HOSPITAIS.ID; hospital do item no momento do alerta.';
COMMENT ON COLUMN ALERTAS.TIPO IS 'CRITICO, ATENCAO ou INFO.';
COMMENT ON COLUMN ALERTAS.MENSAGEM IS 'Texto do alerta com os valores do momento em que foi gerado.';
COMMENT ON COLUMN ALERTAS.ORIGEM IS 'Local de armazenamento do item.';
COMMENT ON COLUMN ALERTAS.CRIADO_EM IS 'Data e hora em que o alerta foi gravado.';

CREATE INDEX IF NOT EXISTS IX_ALERTA_ITEM_DATA ON ALERTAS (ITEM_ESTOQUE_ID, CRIADO_EM);
CREATE INDEX IF NOT EXISTS IX_ALERTA_HOSPITAL ON ALERTAS (HOSPITAL_ID);

-- -----------------------------------------------------------------------------
-- VIEW vw_alertas_vigentes
--
-- Alertas que ainda valem para a situacao atual do estoque, usada pela tela
-- de Alertas do back-end. Considera os alertas registrados hoje pela
-- procedure, pega o mais recente de cada item por categoria (estoque ou
-- validade) e descarta os que deixaram de valer (ex.: item reposto depois
-- do alerta de estoque critico).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_alertas_vigentes AS
SELECT item_estoque_id, item_nome, hospital_id, hospital_nome,
       tipo, mensagem, local_armazenamento, criado_em
  FROM (
        SELECT a.item_estoque_id,
               ie.nome                AS item_nome,
               h.id                   AS hospital_id,
               h.nome                 AS hospital_nome,
               a.tipo,
               a.mensagem,
               ie.local_armazenamento,
               a.criado_em,
               ie.quantidade_atual,
               ie.quantidade_minima,
               ie.validade,
               CASE WHEN a.mensagem LIKE 'Estoque%' THEN 'ESTOQUE' ELSE 'VALIDADE' END AS categoria,
               ROW_NUMBER() OVER (
                   PARTITION BY a.item_estoque_id,
                                CASE WHEN a.mensagem LIKE 'Estoque%' THEN 'ESTOQUE' ELSE 'VALIDADE' END
                   ORDER BY a.criado_em DESC, a.id DESC
               ) AS ordem
          FROM alertas a
          JOIN itens_estoque ie ON ie.id = a.item_estoque_id
          JOIN hospitais h      ON h.id  = ie.hospital_id
         WHERE a.criado_em >= TRUNC(SYSDATE)
       )
 WHERE ordem = 1
   AND (
           (categoria = 'ESTOQUE'
            AND tipo = CASE
                           WHEN quantidade_atual <= quantidade_minima       THEN 'CRITICO'
                           WHEN quantidade_atual <= quantidade_minima * 1.5 THEN 'ATENCAO'
                       END)
        OR (categoria = 'VALIDADE' AND mensagem LIKE 'Item vencido%'
            AND validade < TRUNC(SYSDATE))
        OR (categoria = 'VALIDADE' AND mensagem LIKE 'Validade proxima%'
            AND validade BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + 60)
       );


-- =============================================================================
-- 2. FUNCTIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- FUNCTION fn_dias_cobertura_estoque
--
-- Proposito:
--   Indicador (KPI) que estima em quantos DIAS o estoque atual de um item se
--   esgota, com base no consumo medio mensal dos ultimos 6 meses registrado em
--   HISTORICO_CONSUMO. Antecipa rupturas antes do nivel minimo ser atingido.
--
-- Parametro (IN):
--   p_item_id - identificador do item em ITENS_ESTOQUE
--
-- Retorno (NUMBER):
--   Dias estimados de cobertura, com 1 casa decimal.
--   NULL quando nao ha historico de consumo para estimar.
--
-- Excecoes:
--   NO_DATA_FOUND - item inexistente          -> ORA-20101
--   OTHERS        - qualquer outra falha      -> ORA-20109
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_dias_cobertura_estoque (
    p_item_id IN itens_estoque.id%TYPE
) RETURN NUMBER
IS
    v_quantidade_atual   itens_estoque.quantidade_atual%TYPE;
    v_consumo_medio_mes  NUMBER;
BEGIN
    -- Garante que o item existe e recupera a quantidade atual
    SELECT quantidade_atual
      INTO v_quantidade_atual
      FROM itens_estoque
     WHERE id = p_item_id;

    -- Consumo medio mensal nos ultimos 6 meses (0 se nao houver historico)
    SELECT NVL(AVG(quantidade_consumida), 0)
      INTO v_consumo_medio_mes
      FROM historico_consumo
     WHERE item_estoque_id = p_item_id
       AND mes_referencia >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6);

    -- Sem consumo registrado nao ha como projetar a cobertura
    IF v_consumo_medio_mes = 0 THEN
        RETURN NULL;
    END IF;

    -- Consumo diario aproximado = consumo mensal / 30
    RETURN ROUND(v_quantidade_atual / (v_consumo_medio_mes / 30), 1);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20101, 'Item de estoque ' || p_item_id || ' nao encontrado.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20109, 'Erro ao calcular dias de cobertura do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_dias_cobertura_estoque;
/


-- -----------------------------------------------------------------------------
-- FUNCTION fn_status_estoque_formatado
--
-- Proposito:
--   Retorna uma linha de texto pronta para exibicao (painel, relatorio ou
--   notificacao) com o nivel do estoque, hospital, quantidades e situacao da
--   validade do item. Ex.:
--   [CRITICO] Dipirona 500mg (Hospital das Clinicas) - 15 cx (min. 50) - vence em 45 dia(s)
--
--   O nivel segue a mesma regra de negocio do back-end (ItemEstoque.calcularNivel):
--     quantidade_atual <= minimo        -> CRITICO
--     quantidade_atual <= minimo * 1.5  -> ATENCAO
--     demais casos                      -> NORMAL
--
-- Parametro (IN):
--   p_item_id - identificador do item em ITENS_ESTOQUE
--
-- Retorno (VARCHAR2):
--   Texto formatado. Para item inexistente retorna mensagem amigavel em vez
--   de erro, permitindo uso seguro dentro de SELECTs.
--
-- Excecoes:
--   NO_DATA_FOUND - item inexistente -> mensagem "nao encontrado"
--   OTHERS        - qualquer falha   -> ORA-20108
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_status_estoque_formatado (
    p_item_id IN itens_estoque.id%TYPE
) RETURN VARCHAR2
IS
    v_nome        itens_estoque.nome%TYPE;
    v_qtd_atual   itens_estoque.quantidade_atual%TYPE;
    v_qtd_minima  itens_estoque.quantidade_minima%TYPE;
    v_unidade     itens_estoque.unidade_medida%TYPE;
    v_validade    itens_estoque.validade%TYPE;
    v_hospital    hospitais.nome%TYPE;
    v_nivel       VARCHAR2(10);
    v_dias_venc   NUMBER;
    v_resultado   VARCHAR2(400);
BEGIN
    SELECT ie.nome, ie.quantidade_atual, ie.quantidade_minima,
           NVL(ie.unidade_medida, 'un.'), ie.validade, h.nome
      INTO v_nome, v_qtd_atual, v_qtd_minima, v_unidade, v_validade, v_hospital
      FROM itens_estoque ie
      JOIN hospitais h ON h.id = ie.hospital_id
     WHERE ie.id = p_item_id;

    IF v_qtd_atual <= v_qtd_minima THEN
        v_nivel := 'CRITICO';
    ELSIF v_qtd_atual <= v_qtd_minima * 1.5 THEN
        v_nivel := 'ATENCAO';
    ELSE
        v_nivel := 'NORMAL';
    END IF;

    v_resultado := '[' || v_nivel || '] ' || v_nome || ' (' || v_hospital || ') - ' ||
                   v_qtd_atual || ' ' || v_unidade || ' (min. ' || v_qtd_minima || ')';

    -- Acrescenta a situacao da validade quando vencido ou a ate 60 dias
    IF v_validade IS NOT NULL THEN
        v_dias_venc := TRUNC(v_validade) - TRUNC(SYSDATE);
        IF v_dias_venc < 0 THEN
            v_resultado := v_resultado || ' - VENCIDO em ' || TO_CHAR(v_validade, 'DD/MM/YYYY');
        ELSIF v_dias_venc <= 60 THEN
            v_resultado := v_resultado || ' - vence em ' || v_dias_venc || ' dia(s)';
        END IF;
    END IF;

    RETURN v_resultado;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Item de estoque ' || p_item_id || ' nao encontrado.';
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20108, 'Erro ao formatar status do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_status_estoque_formatado;
/



-- =============================================================================
-- 3. PROCEDURES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PROCEDURE prc_registrar_alertas_criticos
--
-- Proposito:
--   Rotina automatizada que varre os itens de estoque e persiste na tabela
--   ALERTAS as situacoes que exigem acao da equipe:
--     - Estoque CRITICO (<= minimo) ou em ATENCAO (<= minimo * 1.5)
--     - Item VENCIDO                          -> alerta CRITICO
--     - Validade em ate 15 dias               -> alerta ATENCAO
--     - Validade entre 16 e 60 dias           -> alerta INFO
--
-- Funcionamento:
--   1. Abre um CURSOR com os itens do hospital informado (ou de todos).
--   2. Em LOOP, classifica cada item com IF/ELSIF.
--   3. Evita duplicidade com o subprograma local registrar_se_novo: so insere
--      se o mesmo alerta (tipo + texto) nao foi gerado hoje. Se a situacao do
--      item muda (ex.: quantidade cai de 150 para 140), um novo alerta e
--      gravado com os valores atuais, formando um historico auditavel.
--   4. Cada item roda em um bloco proprio com EXCEPTION, entao a falha de um
--      item e registrada via DBMS_OUTPUT e nao interrompe os demais.
--   5. Devolve a quantidade de alertas criados. Nao faz COMMIT/ROLLBACK:
--      a transacao pertence a quem chamou (mesmo padrao de PR_REGISTRAR_CONSUMO).
--
-- Acionamento pelo back-end (Java):
--   Chamada via JDBC (SimpleJdbcCall) sempre que um item de estoque e criado
--   ou atualizado (evento EstoqueAlteradoEvent), na inicializacao da API,
--   diariamente as 00:05 (rotina agendada) e pelo endpoint
--   POST /api/plsql/alertas/processar.
--   A tela de Alertas do app le o resultado pela view VW_ALERTAS_VIGENTES.
--
-- Parametros:
--   p_hospital_id   (IN, opcional) - restringe a um hospital; NULL = todos
--   p_total_alertas (OUT)          - quantidade de alertas novos registrados
--
-- Excecoes:
--   OTHERS (geral) - ORA-20110
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_registrar_alertas_criticos (
    p_hospital_id    IN  itens_estoque.hospital_id%TYPE DEFAULT NULL,
    p_total_alertas  OUT NUMBER
)
IS
    CURSOR c_itens IS
        SELECT ie.id, ie.nome, ie.quantidade_atual, ie.quantidade_minima,
               NVL(ie.unidade_medida, 'un.') AS unidade,
               ie.validade, ie.hospital_id, ie.local_armazenamento
          FROM itens_estoque ie
         WHERE p_hospital_id IS NULL
            OR ie.hospital_id = p_hospital_id;

    v_nivel          VARCHAR2(10);
    v_dias_venc      NUMBER;
    v_total_alertas  PLS_INTEGER := 0;

    -- Subprograma local: grava o alerta somente se o mesmo alerta (tipo e
    -- texto) ainda nao foi registrado hoje para o item
    PROCEDURE registrar_se_novo (
        p_item_id   IN alertas.item_estoque_id%TYPE,
        p_hosp_id   IN alertas.hospital_id%TYPE,
        p_tipo      IN alertas.tipo%TYPE,
        p_mensagem  IN alertas.mensagem%TYPE,
        p_origem    IN alertas.origem%TYPE
    ) IS
        v_ja_registrado NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_ja_registrado
          FROM alertas
         WHERE item_estoque_id = p_item_id
           AND tipo = p_tipo
           AND mensagem = p_mensagem
           AND criado_em >= TRUNC(SYSDATE);

        IF v_ja_registrado = 0 THEN
            INSERT INTO alertas (item_estoque_id, hospital_id, tipo, mensagem, origem)
            VALUES (p_item_id, p_hosp_id, p_tipo, p_mensagem, p_origem);
            v_total_alertas := v_total_alertas + 1;
        END IF;
    END registrar_se_novo;
BEGIN
    FOR r_item IN c_itens LOOP
        BEGIN
            -- 1) Alerta de nivel de estoque
            IF r_item.quantidade_atual <= r_item.quantidade_minima THEN
                v_nivel := 'CRITICO';
            ELSIF r_item.quantidade_atual <= r_item.quantidade_minima * 1.5 THEN
                v_nivel := 'ATENCAO';
            ELSE
                v_nivel := NULL;
            END IF;

            IF v_nivel IS NOT NULL THEN
                registrar_se_novo(
                    r_item.id, r_item.hospital_id, v_nivel,
                    'Estoque ' || LOWER(v_nivel) || ': ' || r_item.quantidade_atual || ' ' ||
                    r_item.unidade || ' (minimo ' || r_item.quantidade_minima || ') - ' || r_item.nome,
                    r_item.local_armazenamento);
            END IF;

            -- 2) Alerta de validade
            IF r_item.validade IS NOT NULL THEN
                v_dias_venc := TRUNC(r_item.validade) - TRUNC(SYSDATE);

                IF v_dias_venc < 0 THEN
                    registrar_se_novo(
                        r_item.id, r_item.hospital_id, 'CRITICO',
                        'Item vencido em ' || TO_CHAR(r_item.validade, 'DD/MM/YYYY') || ' - ' || r_item.nome,
                        r_item.local_armazenamento);
                ELSIF v_dias_venc <= 60 THEN
                    registrar_se_novo(
                        r_item.id, r_item.hospital_id,
                        CASE WHEN v_dias_venc <= 15 THEN 'ATENCAO' ELSE 'INFO' END,
                        'Validade proxima: vence em ' || v_dias_venc || ' dia(s) - ' || r_item.nome,
                        r_item.local_armazenamento);
                END IF;
            END IF;

        EXCEPTION
            -- Falha isolada de um item nao interrompe o processamento dos demais
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Falha ao processar item ' || r_item.id || ': ' || SQLERRM);
        END;
    END LOOP;

    p_total_alertas := v_total_alertas;
    DBMS_OUTPUT.PUT_LINE(v_total_alertas || ' alerta(s) novo(s) registrado(s).');

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20110, 'Erro ao registrar alertas criticos: ' || SQLERRM);
END prc_registrar_alertas_criticos;
/


-- -----------------------------------------------------------------------------
-- PROCEDURE prc_relatorio_consumo_hospital
--
-- Proposito:
--   Gera o relatorio resumido de consumo de um hospital em um mes: totais
--   consolidados (parametros OUT) e o detalhamento por item, com custo,
--   devolvido em um SYS_REFCURSOR para ser percorrido pelo chamador
--   (bloco PL/SQL, SQL Developer ou o back-end Java via JDBC).
--
-- Funcionamento:
--   1. Valida se o hospital existe (senao ORA-20120).
--   2. Calcula a quantidade de itens distintos, o total de unidades e o custo
--      total consumido no mes de referencia.
--   3. Abre o cursor com o detalhamento ordenado do maior para o menor consumo.
--
-- Acionamento pelo back-end (Java):
--   GET /api/plsql/relatorios/consumo/{hospitalId}?mes=AAAA-MM
--
-- Parametros:
--   p_hospital_id     (IN)  - hospital do relatorio
--   p_mes_referencia  (IN)  - qualquer data do mes desejado
--   p_total_itens     (OUT) - itens distintos consumidos no mes
--   p_total_consumido (OUT) - soma das unidades consumidas
--   p_custo_total     (OUT) - soma do custo (quantidade * custo_unitario)
--   p_cursor          (OUT) - detalhamento: item, quantidade, unidade,
--                             custo_unitario, custo_total
--
-- Excecoes:
--   Hospital inexistente -> ORA-20120
--   OTHERS               -> fecha o cursor, se aberto, e ORA-20121
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_relatorio_consumo_hospital (
    p_hospital_id      IN  hospitais.id%TYPE,
    p_mes_referencia   IN  DATE,
    p_total_itens      OUT NUMBER,
    p_total_consumido  OUT NUMBER,
    p_custo_total      OUT NUMBER,
    p_cursor           OUT SYS_REFCURSOR
)
IS
    v_existe  NUMBER;
    e_hospital_inexistente EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO v_existe FROM hospitais WHERE id = p_hospital_id;
    IF v_existe = 0 THEN
        RAISE e_hospital_inexistente;
    END IF;

    SELECT COUNT(DISTINCT hc.item_estoque_id),
           NVL(SUM(hc.quantidade_consumida), 0),
           NVL(SUM(ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2)), 0)
      INTO p_total_itens, p_total_consumido, p_custo_total
      FROM historico_consumo hc
      JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
     WHERE hc.hospital_id = p_hospital_id
       AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM');

    OPEN p_cursor FOR
        SELECT ie.nome                                                       AS item,
               hc.quantidade_consumida                                       AS quantidade,
               NVL(ie.unidade_medida, 'un.')                                 AS unidade,
               ie.custo_unitario                                             AS custo_unitario,
               ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2) AS custo_total
          FROM historico_consumo hc
          JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
         WHERE hc.hospital_id = p_hospital_id
           AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM')
         ORDER BY hc.quantidade_consumida DESC;

EXCEPTION
    WHEN e_hospital_inexistente THEN
        RAISE_APPLICATION_ERROR(-20120, 'Hospital ' || p_hospital_id || ' nao encontrado.');
    WHEN OTHERS THEN
        IF p_cursor%ISOPEN THEN
            CLOSE p_cursor;
        END IF;
        RAISE_APPLICATION_ERROR(-20121, 'Erro ao gerar relatorio de consumo do hospital ' ||
                                        p_hospital_id || ': ' || SQLERRM);
END prc_relatorio_consumo_hospital;
/



PROMPT Objetos da Parte 3: esperado VALID
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN ('ALERTAS', 'VW_ALERTAS_VIGENTES',
                       'FN_DIAS_COBERTURA_ESTOQUE', 'FN_STATUS_ESTOQUE_FORMATADO',
                       'PRC_REGISTRAR_ALERTAS_CRITICOS', 'PRC_RELATORIO_CONSUMO_HOSPITAL')
 ORDER BY OBJECT_TYPE, OBJECT_NAME;
