-- =============================================================================
-- MediStock (Smart HAS) - Camada de persistencia Oracle + PL/SQL
--
-- Conteudo:
--   1. Limpeza dos objetos (script pode ser reexecutado)
--   2. DDL das tabelas (espelha as entidades JPA do back-end + tabela ALERTAS)
--   3. Dados simulados
--   4. Functions  : fn_dias_cobertura_estoque, fn_status_estoque_formatado
--   5. Procedures : prc_registrar_alertas_criticos, prc_relatorio_consumo_hospital
--   6. Exemplos de uso das functions em consultas e das procedures
--
-- Integracao com o back-end (Spring Boot, profile "oracle"):
--   - Ao criar/atualizar um item de estoque, o back-end publica um evento e,
--     apos o commit, chama prc_registrar_alertas_criticos via JDBC.
--   - Endpoints em /api/plsql expoem as procedures e as functions.
-- =============================================================================

SET SERVEROUTPUT ON;


-- =============================================================================
-- 1. LIMPEZA
-- =============================================================================
BEGIN
    FOR obj IN (
        SELECT object_name, object_type
          FROM user_objects
         WHERE object_name IN (
                   'PRC_REGISTRAR_ALERTAS_CRITICOS', 'PRC_RELATORIO_CONSUMO_HOSPITAL',
                   'FN_DIAS_COBERTURA_ESTOQUE', 'FN_STATUS_ESTOQUE_FORMATADO'
               )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP ' || obj.object_type || ' ' || obj.object_name;
    END LOOP;

    FOR tab IN (
        SELECT table_name
          FROM user_tables
         WHERE table_name IN ('ALERTAS', 'ENTREGAS', 'TRANSFERENCIAS', 'HISTORICO_CONSUMO',
                              'ITENS_ESTOQUE', 'USUARIOS', 'HOSPITAIS')
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || tab.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/


-- =============================================================================
-- 2. DDL
-- Colunas booleanas usam NUMBER(1) (0/1), o mesmo mapeamento do Hibernate
-- para "boolean" no Oracle, permitindo que o back-end use estas tabelas.
-- =============================================================================

CREATE TABLE hospitais (
    id         NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(150)  NOT NULL,
    endereco   VARCHAR2(200),
    cidade     VARCHAR2(80),
    estado     VARCHAR2(2),
    latitude   NUMBER         NOT NULL,
    longitude  NUMBER         NOT NULL
);

CREATE TABLE usuarios (
    id                   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primeiro_nome        VARCHAR2(80)   NOT NULL,
    ultimo_nome          VARCHAR2(80)   NOT NULL,
    email_institucional  VARCHAR2(150)  NOT NULL,
    senha_hash           VARCHAR2(255)  NOT NULL,
    criado_em            TIMESTAMP      NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email_institucional)
);

CREATE TABLE itens_estoque (
    id                        NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                      VARCHAR2(150)  NOT NULL,
    quantidade_atual          NUMBER(10)     NOT NULL,
    quantidade_minima         NUMBER(10)     NOT NULL,
    unidade_medida            VARCHAR2(20),
    local_armazenamento       VARCHAR2(150),
    hospital_id               NUMBER         NOT NULL,
    validade                  DATE,
    custo_unitario            NUMBER(12,2),
    alto_custo_baixa_demanda  NUMBER(1)      DEFAULT 0 NOT NULL
                              CHECK (alto_custo_baixa_demanda IN (0, 1)),
    atualizado_em             TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_item_hospital FOREIGN KEY (hospital_id) REFERENCES hospitais(id)
);

CREATE TABLE historico_consumo (
    id                    NUMBER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_estoque_id       NUMBER      NOT NULL,
    hospital_id           NUMBER      NOT NULL,
    mes_referencia        DATE        NOT NULL,
    quantidade_consumida  NUMBER(10)  NOT NULL,
    CONSTRAINT fk_hist_item FOREIGN KEY (item_estoque_id) REFERENCES itens_estoque(id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_hosp FOREIGN KEY (hospital_id)     REFERENCES hospitais(id)
);

CREATE TABLE transferencias (
    id                   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_estoque_id      NUMBER         NOT NULL,
    hospital_origem_id   NUMBER         NOT NULL,
    hospital_destino_id  NUMBER         NOT NULL,
    quantidade           NUMBER(10)     NOT NULL,
    status               VARCHAR2(20)   DEFAULT 'PENDENTE' NOT NULL
                         CHECK (status IN ('PENDENTE', 'EM_ROTA', 'CONCLUIDA', 'CANCELADA')),
    distancia_km         NUMBER,
    tempo_estimado_min   NUMBER,
    motivo               VARCHAR2(300),
    gerado_por_ia        NUMBER(1)      DEFAULT 0 NOT NULL CHECK (gerado_por_ia IN (0, 1)),
    criado_em            TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_transf_item    FOREIGN KEY (item_estoque_id)     REFERENCES itens_estoque(id) ON DELETE CASCADE,
    CONSTRAINT fk_transf_origem  FOREIGN KEY (hospital_origem_id)  REFERENCES hospitais(id),
    CONSTRAINT fk_transf_destino FOREIGN KEY (hospital_destino_id) REFERENCES hospitais(id)
);

CREATE TABLE entregas (
    id                   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_estoque_id      NUMBER         NOT NULL,
    hospital_destino_id  NUMBER         NOT NULL,
    quantidade           NUMBER(10)     NOT NULL,
    status               VARCHAR2(20)   DEFAULT 'PENDENTE' NOT NULL
                         CHECK (status IN ('PENDENTE', 'EM_ROTA', 'CONCLUIDA', 'CANCELADA')),
    data_prevista        DATE,
    transportadora       VARCHAR2(150),
    criado_em            TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_entrega_item    FOREIGN KEY (item_estoque_id)     REFERENCES itens_estoque(id) ON DELETE CASCADE,
    CONSTRAINT fk_entrega_destino FOREIGN KEY (hospital_destino_id) REFERENCES hospitais(id)
);

-- Tabela exclusiva da camada PL/SQL: alertas persistidos pela procedure
-- prc_registrar_alertas_criticos (historico auditavel de alertas).
CREATE TABLE alertas (
    id               NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_estoque_id  NUMBER,
    hospital_id      NUMBER,
    tipo             VARCHAR2(20)   NOT NULL CHECK (tipo IN ('CRITICO', 'ATENCAO', 'INFO')),
    mensagem         VARCHAR2(400)  NOT NULL,
    origem           VARCHAR2(150),
    criado_em        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_alerta_item FOREIGN KEY (item_estoque_id) REFERENCES itens_estoque(id) ON DELETE CASCADE,
    CONSTRAINT fk_alerta_hosp FOREIGN KEY (hospital_id)     REFERENCES hospitais(id)
);

CREATE INDEX ix_itens_hospital  ON itens_estoque (hospital_id);
CREATE INDEX ix_hist_item_mes   ON historico_consumo (item_estoque_id, mes_referencia);
CREATE INDEX ix_hist_hosp_mes   ON historico_consumo (hospital_id, mes_referencia);
CREATE INDEX ix_alertas_item    ON alertas (item_estoque_id, criado_em);


-- =============================================================================
-- 3. DADOS SIMULADOS
-- Validades relativas a SYSDATE para que todos os cenarios de alerta
-- (vencido, vence em ate 15 dias, vence em ate 60 dias) aparecam sempre.
-- =============================================================================

INSERT INTO hospitais (nome, endereco, cidade, estado, latitude, longitude)
VALUES ('Hospital das Clinicas', 'Av. Dr. Eneas de Carvalho Aguiar, 255', 'Sao Paulo', 'SP', -23.5570, -46.6695);
INSERT INTO hospitais (nome, endereco, cidade, estado, latitude, longitude)
VALUES ('Hospital Regional do ABC', 'Av. Industrial, 3100', 'Santo Andre', 'SP', -23.6644, -46.5383);

-- Itens do Hospital 1 (ids 1 a 3)
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario)
VALUES ('Dipirona 500mg', 15, 50, 'cx', 'Almoxarifado A - Prateleira 3', 1, TRUNC(SYSDATE) + 45, 12.50);
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario)
VALUES ('Soro Fisiologico 500ml', 480, 200, 'un', 'Almoxarifado A - Prateleira 1', 1, ADD_MONTHS(TRUNC(SYSDATE), 9), 4.30);
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario)
VALUES ('Luvas Latex M', 140, 100, 'cx', 'Almoxarifado B - Prateleira 2', 1, TRUNC(SYSDATE) + 10, 22.00);

-- Itens do Hospital 2 (ids 4 a 6)
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario)
VALUES ('Paracetamol 750mg', 300, 120, 'cx', 'Farmacia Central', 2, ADD_MONTHS(TRUNC(SYSDATE), 4), 9.90);
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario, alto_custo_baixa_demanda)
VALUES ('Insulina NPH', 8, 10, 'un', 'Camara Fria', 2, TRUNC(SYSDATE) - 3, 45.00, 1);
INSERT INTO itens_estoque (nome, quantidade_atual, quantidade_minima, unidade_medida, local_armazenamento, hospital_id, validade, custo_unitario)
VALUES ('Dipirona 500mg', 400, 80, 'cx', 'Farmacia Central', 2, ADD_MONTHS(TRUNC(SYSDATE), 6), 12.50);

-- Historico de consumo (referenciado no primeiro dia do mes)
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (1, 1, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2), 40);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (1, 1, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1), 55);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (1, 1, TRUNC(SYSDATE, 'MM'), 60);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (2, 1, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1), 300);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (2, 1, TRUNC(SYSDATE, 'MM'), 250);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (3, 1, TRUNC(SYSDATE, 'MM'), 90);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (4, 2, ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1), 130);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (4, 2, TRUNC(SYSDATE, 'MM'), 150);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (5, 2, TRUNC(SYSDATE, 'MM'), 12);
INSERT INTO historico_consumo (item_estoque_id, hospital_id, mes_referencia, quantidade_consumida) VALUES (6, 2, TRUNC(SYSDATE, 'MM'), 70);

-- Transferencia sugerida: Dipirona do Hospital 2 (item 6, estoque alto) para o Hospital 1 (critico)
INSERT INTO transferencias (item_estoque_id, hospital_origem_id, hospital_destino_id, quantidade, status, distancia_km, tempo_estimado_min, motivo, gerado_por_ia)
VALUES (6, 2, 1, 40, 'PENDENTE', 18.4, 32, 'Reposicao automatica sugerida por nivel critico no Hospital das Clinicas', 1);

INSERT INTO entregas (item_estoque_id, hospital_destino_id, quantidade, status, data_prevista, transportadora)
VALUES (5, 2, 30, 'EM_ROTA', TRUNC(SYSDATE) + 2, 'MedLog Transportes');

COMMIT;


-- =============================================================================
-- 4. FUNCTIONS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- FUNCTION fn_dias_cobertura_estoque
--
-- Proposito:
--   Indicador (KPI) que estima em quantos DIAS o estoque atual de um item se
--   esgota, com base no consumo medio mensal dos ultimos 6 meses registrado em
--   HISTORICO_CONSUMO. Antecipa rupturas antes do nivel minimo ser atingido.
--
-- Parametro (IN):
--   p_item_id - identificador do item em ITENS_ESTOQUE
--
-- Retorno (NUMBER):
--   Dias estimados de cobertura, com 1 casa decimal.
--   NULL quando nao ha historico de consumo para estimar.
--
-- Excecoes:
--   NO_DATA_FOUND - item inexistente          -> ORA-20001
--   OTHERS        - qualquer outra falha      -> ORA-20099
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_dias_cobertura_estoque (
    p_item_id IN itens_estoque.id%TYPE
) RETURN NUMBER
IS
    v_quantidade_atual   itens_estoque.quantidade_atual%TYPE;
    v_consumo_medio_mes  NUMBER;
BEGIN
    -- Garante que o item existe e recupera a quantidade atual
    SELECT quantidade_atual
      INTO v_quantidade_atual
      FROM itens_estoque
     WHERE id = p_item_id;

    -- Consumo medio mensal nos ultimos 6 meses (0 se nao houver historico)
    SELECT NVL(AVG(quantidade_consumida), 0)
      INTO v_consumo_medio_mes
      FROM historico_consumo
     WHERE item_estoque_id = p_item_id
       AND mes_referencia >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6);

    -- Sem consumo registrado nao ha como projetar a cobertura
    IF v_consumo_medio_mes = 0 THEN
        RETURN NULL;
    END IF;

    -- Consumo diario aproximado = consumo mensal / 30
    RETURN ROUND(v_quantidade_atual / (v_consumo_medio_mes / 30), 1);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Item de estoque ' || p_item_id || ' nao encontrado.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20099, 'Erro ao calcular dias de cobertura do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_dias_cobertura_estoque;
/


-- -----------------------------------------------------------------------------
-- FUNCTION fn_status_estoque_formatado
--
-- Proposito:
--   Retorna uma linha de texto pronta para exibicao (painel, relatorio ou
--   notificacao) com o nivel do estoque, hospital, quantidades e situacao da
--   validade do item. Ex.:
--   [CRITICO] Dipirona 500mg (Hospital das Clinicas) - 15 cx (min. 50) - vence em 45 dia(s)
--
--   O nivel segue a mesma regra de negocio do back-end (ItemEstoque.calcularNivel):
--     quantidade_atual <= minimo        -> CRITICO
--     quantidade_atual <= minimo * 1.5  -> ATENCAO
--     demais casos                      -> NORMAL
--
-- Parametro (IN):
--   p_item_id - identificador do item em ITENS_ESTOQUE
--
-- Retorno (VARCHAR2):
--   Texto formatado. Para item inexistente retorna mensagem amigavel em vez
--   de erro, permitindo uso seguro dentro de SELECTs.
--
-- Excecoes:
--   NO_DATA_FOUND - item inexistente -> mensagem "nao encontrado"
--   OTHERS        - qualquer falha   -> ORA-20098
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_status_estoque_formatado (
    p_item_id IN itens_estoque.id%TYPE
) RETURN VARCHAR2
IS
    v_nome        itens_estoque.nome%TYPE;
    v_qtd_atual   itens_estoque.quantidade_atual%TYPE;
    v_qtd_minima  itens_estoque.quantidade_minima%TYPE;
    v_unidade     itens_estoque.unidade_medida%TYPE;
    v_validade    itens_estoque.validade%TYPE;
    v_hospital    hospitais.nome%TYPE;
    v_nivel       VARCHAR2(10);
    v_dias_venc   NUMBER;
    v_resultado   VARCHAR2(400);
BEGIN
    SELECT ie.nome, ie.quantidade_atual, ie.quantidade_minima,
           NVL(ie.unidade_medida, 'un.'), ie.validade, h.nome
      INTO v_nome, v_qtd_atual, v_qtd_minima, v_unidade, v_validade, v_hospital
      FROM itens_estoque ie
      JOIN hospitais h ON h.id = ie.hospital_id
     WHERE ie.id = p_item_id;

    IF v_qtd_atual <= v_qtd_minima THEN
        v_nivel := 'CRITICO';
    ELSIF v_qtd_atual <= v_qtd_minima * 1.5 THEN
        v_nivel := 'ATENCAO';
    ELSE
        v_nivel := 'NORMAL';
    END IF;

    v_resultado := '[' || v_nivel || '] ' || v_nome || ' (' || v_hospital || ') - ' ||
                   v_qtd_atual || ' ' || v_unidade || ' (min. ' || v_qtd_minima || ')';

    -- Acrescenta a situacao da validade quando vencido ou a ate 60 dias
    IF v_validade IS NOT NULL THEN
        v_dias_venc := TRUNC(v_validade) - TRUNC(SYSDATE);
        IF v_dias_venc < 0 THEN
            v_resultado := v_resultado || ' - VENCIDO em ' || TO_CHAR(v_validade, 'DD/MM/YYYY');
        ELSIF v_dias_venc <= 60 THEN
            v_resultado := v_resultado || ' - vence em ' || v_dias_venc || ' dia(s)';
        END IF;
    END IF;

    RETURN v_resultado;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Item de estoque ' || p_item_id || ' nao encontrado.';
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20098, 'Erro ao formatar status do item ' ||
                                        p_item_id || ': ' || SQLERRM);
END fn_status_estoque_formatado;
/


-- =============================================================================
-- 5. PROCEDURES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- PROCEDURE prc_registrar_alertas_criticos
--
-- Proposito:
--   Rotina automatizada que varre os itens de estoque e persiste na tabela
--   ALERTAS as situacoes que exigem acao da equipe:
--     - Estoque CRITICO (<= minimo) ou em ATENCAO (<= minimo * 1.5)
--     - Item VENCIDO                          -> alerta CRITICO
--     - Validade em ate 15 dias               -> alerta ATENCAO
--     - Validade entre 16 e 60 dias           -> alerta INFO
--
-- Funcionamento:
--   1. Abre um CURSOR com os itens do hospital informado (ou de todos).
--   2. Em LOOP, classifica cada item com IF/ELSIF.
--   3. Evita duplicidade: so insere se o mesmo alerta nao foi gerado hoje.
--   4. Cada item roda em um bloco proprio com EXCEPTION, entao a falha de um
--      item e registrada via DBMS_OUTPUT e nao interrompe os demais.
--   5. Faz COMMIT ao final e devolve a quantidade de alertas criados.
--
-- Acionamento pelo back-end (Java):
--   Chamada via JDBC (SimpleJdbcCall) sempre que um item de estoque e criado
--   ou atualizado (evento EstoqueAlteradoEvent) e pelo endpoint
--   POST /api/plsql/alertas/processar.
--
-- Parametros:
--   p_hospital_id   (IN, opcional) - restringe a um hospital; NULL = todos
--   p_total_alertas (OUT)          - quantidade de alertas novos registrados
--
-- Excecoes:
--   OTHERS (geral) - ROLLBACK e ORA-20010
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_registrar_alertas_criticos (
    p_hospital_id    IN  itens_estoque.hospital_id%TYPE DEFAULT NULL,
    p_total_alertas  OUT NUMBER
)
IS
    CURSOR c_itens IS
        SELECT ie.id, ie.nome, ie.quantidade_atual, ie.quantidade_minima,
               NVL(ie.unidade_medida, 'un.') AS unidade,
               ie.validade, ie.hospital_id, ie.local_armazenamento
          FROM itens_estoque ie
         WHERE p_hospital_id IS NULL
            OR ie.hospital_id = p_hospital_id;

    v_nivel          VARCHAR2(10);
    v_dias_venc      NUMBER;
    v_ja_registrado  NUMBER;
    v_total_alertas  PLS_INTEGER := 0;
BEGIN
    FOR r_item IN c_itens LOOP
        BEGIN
            -- 1) Alerta de nivel de estoque
            IF r_item.quantidade_atual <= r_item.quantidade_minima THEN
                v_nivel := 'CRITICO';
            ELSIF r_item.quantidade_atual <= r_item.quantidade_minima * 1.5 THEN
                v_nivel := 'ATENCAO';
            ELSE
                v_nivel := NULL;
            END IF;

            IF v_nivel IS NOT NULL THEN
                SELECT COUNT(*)
                  INTO v_ja_registrado
                  FROM alertas
                 WHERE item_estoque_id = r_item.id
                   AND tipo = v_nivel
                   AND mensagem LIKE 'Estoque%'
                   AND TRUNC(criado_em) = TRUNC(SYSDATE);

                IF v_ja_registrado = 0 THEN
                    INSERT INTO alertas (item_estoque_id, hospital_id, tipo, mensagem, origem)
                    VALUES (r_item.id, r_item.hospital_id, v_nivel,
                            'Estoque ' || LOWER(v_nivel) || ': ' || r_item.quantidade_atual || ' ' ||
                            r_item.unidade || ' (minimo ' || r_item.quantidade_minima || ') - ' || r_item.nome,
                            r_item.local_armazenamento);
                    v_total_alertas := v_total_alertas + 1;
                END IF;
            END IF;

            -- 2) Alerta de validade
            IF r_item.validade IS NOT NULL THEN
                v_dias_venc := TRUNC(r_item.validade) - TRUNC(SYSDATE);

                IF v_dias_venc < 0 THEN
                    SELECT COUNT(*)
                      INTO v_ja_registrado
                      FROM alertas
                     WHERE item_estoque_id = r_item.id
                       AND mensagem LIKE 'Item vencido%'
                       AND TRUNC(criado_em) = TRUNC(SYSDATE);

                    IF v_ja_registrado = 0 THEN
                        INSERT INTO alertas (item_estoque_id, hospital_id, tipo, mensagem, origem)
                        VALUES (r_item.id, r_item.hospital_id, 'CRITICO',
                                'Item vencido em ' || TO_CHAR(r_item.validade, 'DD/MM/YYYY') ||
                                ' - ' || r_item.nome,
                                r_item.local_armazenamento);
                        v_total_alertas := v_total_alertas + 1;
                    END IF;

                ELSIF v_dias_venc <= 60 THEN
                    SELECT COUNT(*)
                      INTO v_ja_registrado
                      FROM alertas
                     WHERE item_estoque_id = r_item.id
                       AND mensagem LIKE 'Validade proxima%'
                       AND TRUNC(criado_em) = TRUNC(SYSDATE);

                    IF v_ja_registrado = 0 THEN
                        INSERT INTO alertas (item_estoque_id, hospital_id, tipo, mensagem, origem)
                        VALUES (r_item.id, r_item.hospital_id,
                                CASE WHEN v_dias_venc <= 15 THEN 'ATENCAO' ELSE 'INFO' END,
                                'Validade proxima: vence em ' || v_dias_venc || ' dia(s) - ' || r_item.nome,
                                r_item.local_armazenamento);
                        v_total_alertas := v_total_alertas + 1;
                    END IF;
                END IF;
            END IF;

        EXCEPTION
            -- Falha isolada de um item nao interrompe o processamento dos demais
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('Falha ao processar item ' || r_item.id || ': ' || SQLERRM);
        END;
    END LOOP;

    COMMIT;

    p_total_alertas := v_total_alertas;
    DBMS_OUTPUT.PUT_LINE(v_total_alertas || ' alerta(s) novo(s) registrado(s).');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20010, 'Erro ao registrar alertas criticos: ' || SQLERRM);
END prc_registrar_alertas_criticos;
/


-- -----------------------------------------------------------------------------
-- PROCEDURE prc_relatorio_consumo_hospital
--
-- Proposito:
--   Gera o relatorio resumido de consumo de um hospital em um mes: totais
--   consolidados (parametros OUT) e o detalhamento por item, com custo,
--   devolvido em um SYS_REFCURSOR para ser percorrido pelo chamador
--   (bloco PL/SQL, SQL Developer ou o back-end Java via JDBC).
--
-- Funcionamento:
--   1. Valida se o hospital existe (senao ORA-20020).
--   2. Calcula a quantidade de itens distintos, o total de unidades e o custo
--      total consumido no mes de referencia.
--   3. Abre o cursor com o detalhamento ordenado do maior para o menor consumo.
--
-- Acionamento pelo back-end (Java):
--   GET /api/plsql/relatorios/consumo/{hospitalId}?mes=AAAA-MM
--
-- Parametros:
--   p_hospital_id     (IN)  - hospital do relatorio
--   p_mes_referencia  (IN)  - qualquer data do mes desejado
--   p_total_itens     (OUT) - itens distintos consumidos no mes
--   p_total_consumido (OUT) - soma das unidades consumidas
--   p_custo_total     (OUT) - soma do custo (quantidade * custo_unitario)
--   p_cursor          (OUT) - detalhamento: item, quantidade, unidade,
--                             custo_unitario, custo_total
--
-- Excecoes:
--   Hospital inexistente -> ORA-20020
--   OTHERS               -> fecha o cursor, se aberto, e ORA-20021
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_relatorio_consumo_hospital (
    p_hospital_id      IN  hospitais.id%TYPE,
    p_mes_referencia   IN  DATE,
    p_total_itens      OUT NUMBER,
    p_total_consumido  OUT NUMBER,
    p_custo_total      OUT NUMBER,
    p_cursor           OUT SYS_REFCURSOR
)
IS
    v_existe  NUMBER;
    e_hospital_inexistente EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO v_existe FROM hospitais WHERE id = p_hospital_id;
    IF v_existe = 0 THEN
        RAISE e_hospital_inexistente;
    END IF;

    SELECT COUNT(DISTINCT hc.item_estoque_id),
           NVL(SUM(hc.quantidade_consumida), 0),
           NVL(SUM(ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2)), 0)
      INTO p_total_itens, p_total_consumido, p_custo_total
      FROM historico_consumo hc
      JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
     WHERE hc.hospital_id = p_hospital_id
       AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM');

    OPEN p_cursor FOR
        SELECT ie.nome                                                       AS item,
               hc.quantidade_consumida                                       AS quantidade,
               NVL(ie.unidade_medida, 'un.')                                 AS unidade,
               ie.custo_unitario                                             AS custo_unitario,
               ROUND(hc.quantidade_consumida * NVL(ie.custo_unitario, 0), 2) AS custo_total
          FROM historico_consumo hc
          JOIN itens_estoque ie ON ie.id = hc.item_estoque_id
         WHERE hc.hospital_id = p_hospital_id
           AND TRUNC(hc.mes_referencia, 'MM') = TRUNC(p_mes_referencia, 'MM')
         ORDER BY hc.quantidade_consumida DESC;

EXCEPTION
    WHEN e_hospital_inexistente THEN
        RAISE_APPLICATION_ERROR(-20020, 'Hospital ' || p_hospital_id || ' nao encontrado.');
    WHEN OTHERS THEN
        IF p_cursor%ISOPEN THEN
            CLOSE p_cursor;
        END IF;
        RAISE_APPLICATION_ERROR(-20021, 'Erro ao gerar relatorio de consumo do hospital ' ||
                                        p_hospital_id || ': ' || SQLERRM);
END prc_relatorio_consumo_hospital;
/


-- =============================================================================
-- 6. EXEMPLOS DE USO
-- =============================================================================

-- 6.1) Function de texto formatado na lista de SELECT
SELECT id,
       nome,
       fn_status_estoque_formatado(id) AS status_formatado
  FROM itens_estoque
 ORDER BY id;

-- 6.2) Function indicador como criterio de filtro (WHERE) e ordenacao:
--      itens que se esgotam em menos de 30 dias
SELECT nome,
       quantidade_atual,
       fn_dias_cobertura_estoque(id) AS dias_cobertura
  FROM itens_estoque
 WHERE NVL(fn_dias_cobertura_estoque(id), 999) < 30
 ORDER BY dias_cobertura;

-- 6.3) As duas functions juntas em um painel por hospital
SELECT h.nome                              AS hospital,
       fn_status_estoque_formatado(ie.id)  AS situacao,
       fn_dias_cobertura_estoque(ie.id)    AS dias_cobertura
  FROM itens_estoque ie
  JOIN hospitais h ON h.id = ie.hospital_id
 ORDER BY h.nome, NVL(fn_dias_cobertura_estoque(ie.id), 999);

-- 6.4) Procedure de alertas para todos os hospitais
DECLARE
    v_total NUMBER;
BEGIN
    prc_registrar_alertas_criticos(p_total_alertas => v_total);
    DBMS_OUTPUT.PUT_LINE('Total retornado: ' || v_total);
END;
/

SELECT id, tipo, mensagem, origem, criado_em
  FROM alertas
 ORDER BY criado_em DESC;

-- 6.5) Reexecucao restrita ao Hospital 2: nao duplica alertas do mesmo dia
DECLARE
    v_total NUMBER;
BEGIN
    prc_registrar_alertas_criticos(p_hospital_id => 2, p_total_alertas => v_total);
END;
/

-- 6.6) Relatorio de consumo do Hospital 1 no mes corrente percorrendo o cursor
DECLARE
    v_total_itens     NUMBER;
    v_total_consumido NUMBER;
    v_custo_total     NUMBER;
    v_cursor          SYS_REFCURSOR;
    v_item            itens_estoque.nome%TYPE;
    v_qtd             NUMBER;
    v_unidade         itens_estoque.unidade_medida%TYPE;
    v_custo_unit      NUMBER;
    v_custo_item      NUMBER;
BEGIN
    prc_relatorio_consumo_hospital(
        p_hospital_id     => 1,
        p_mes_referencia  => SYSDATE,
        p_total_itens     => v_total_itens,
        p_total_consumido => v_total_consumido,
        p_custo_total     => v_custo_total,
        p_cursor          => v_cursor
    );

    DBMS_OUTPUT.PUT_LINE('--- Relatorio de consumo - Hospital 1 ---');
    DBMS_OUTPUT.PUT_LINE('Itens distintos consumidos: ' || v_total_itens);
    DBMS_OUTPUT.PUT_LINE('Total de unidades consumidas: ' || v_total_consumido);
    DBMS_OUTPUT.PUT_LINE('Custo total: R$ ' || TO_CHAR(v_custo_total, 'FM999G999G990D00'));

    LOOP
        FETCH v_cursor INTO v_item, v_qtd, v_unidade, v_custo_unit, v_custo_item;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' - ' || v_item || ': ' || v_qtd || ' ' || v_unidade ||
                             ' (custo total: R$ ' || TO_CHAR(v_custo_item, 'FM999G999G990D00') || ')');
    END LOOP;
    CLOSE v_cursor;
END;
/

-- 6.7) Tratamento de erro: hospital inexistente dispara ORA-20020
DECLARE
    v_total_itens     NUMBER;
    v_total_consumido NUMBER;
    v_custo_total     NUMBER;
    v_cursor          SYS_REFCURSOR;
BEGIN
    prc_relatorio_consumo_hospital(99, SYSDATE, v_total_itens, v_total_consumido, v_custo_total, v_cursor);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro esperado capturado: ' || SQLERRM);
END;
/
